const cats = {};

// replace category names, keep quotes
// paste lists between [] on the right side of the equal sign
// example: cats["category name"] = ["item 1", "item 2", "item 3", ...];

cats["songs from katsu's \"welcome to my twisted mind\" playlist"] = ["all in my head", "broad shoulders", "call me what you like", "cognitive dissonance", "god complex", "i always wanna die (sometimes)", "i got this feeling that won't let go", "i miss having sex but at least i don't wanna die anymore", "i think i need therapy!", "kiss already!", "not joking", "people fuel", "pet with the tism", "praise", "punch drunk love", "put you through me", "speed", "stupidfreak", "suicide hotline", "super mall mannequin", "too far gone", "way too loud", "where tf did i park my car", "year of the optimist", "you don't like me like that"];

cats["katsu journal entry titles"] = ["// mr. lonely", "cheesecake insomnia", "crashing waves", "desire and scope", "fish shirt friday", "flighty productivity", "four-leaf clover-type beat", "i feel everything", "i sea a future with you", "i'm a cat, sitting", "in/dependence", "low sanity, boosted gay", "mario kart closure", "return to nightmareland", "sick dreams", "smells like summer", "soft & happy", "studious era", "summery summary", "sunsets & sunrises", "t-boy swag", "there may be kittens", "walking forward ... w", "winter loneliness", "winter wishes"];

cats["music albums & EPs"] = ["a dream through open eyes", "bury me at makeout creek", "character development", "dreamland", "falling for robots & wishing i was one", "glitterbug", "guts", "hold the girl", "i like it when you sleep, for you are so beautiful yet so unaware of it", "i love my girl, she's my boy", "internet hometown hero", "it's a funny thing", "man's best friend", "play the game", "ponyboy", "sunrise city", "take me home", "the loneliest time", "the renewal project", "the tortured poets department", "timely!!", "twin fantasy", "workin' on lovin'", "worlds", "your majesty"];

cats["katsu playlist titles"] = ["conversations between friends", "everything that makes sound", "gender theory", "growing pains", "heArt block", "hello summer,", "in every universe", "internet explorer", "isn't that sweet¿", "it's my angst and i get to choose the music", "karaoke neue", "katsu klassic", "late summer drive", "lifetimes", "my heart is an open book", "no peak high enough", "no u-turns // pipe dreams", "press any button", "spelunking", "spelunking", "spring forward//fall into me", "starbound (reprise)", "the taste of crushing & being crushed", "the thought of you thinking of me", "turn the tv up"];

cats["katsu's comfort foods"] = ["bean sprouts", "bibimbap", "breakfast burger", "breakfast burrito", "butter noodles", "chicken noodle soup", "chicken tendies", "clam chowder", "crispy chow mein", "egg drop soup", "filipino spaghetti", "fish n chips", "french fries", "fried rice", "kare-kare", "kimchi stew", "mac n cheese", "omelette", "pancakes", "pretzel bits", "ramen", "shrimp", "tonkatsu", "udon", "waffles"];

cats["katsu's favorite desserts"] = ["brown sugar milk boba", "buko pandan", "butter pecan ice cream", "butter pecan pie", "chocolate-covered ice cream bars", "cream puffs", "flan", "fruit popsicles", "green tea ice cream", "halo-halo", "hawaiian shaved ice", "ice cream cake", "macarons", "mango bingsoo", "mango rème brûlée cake", "mango sticky rice", "mitsumame", "mochi ice cream", "portos tres leches cake", "sago gulaman", "strawberry shortcake/cheesecake", "taho", "tres leches pandan ice cream", "ube ice cream", "vanilla ice cream"];

cats["inedible things that katsu wants to eat"] = ["aquarium pebbles", "bath bombs", "chapstick", "cleaning putty", "cute erasers", "dandelion puffs", "dice", "go stones", "hair bleach mixture", "lava", "lava lamp bubbles", "legos", "marbles", "most flowers", "orange quartz", "paint", "paper confetti", "puzzle pieces", "resin keycaps", "scented shampoo", "seaglass", "soap bars", "sunscreen", "violin rosin", "wooden blocks"];

cats["fruits that have a worth-it deliciousness-to-allergy ratio"] = ["apricot", "asian pear", "bell pepper", "blueberry", "coconut", "green apple", "jackfruit", "kumquat", "lemon", "lime", "longan", "lychee", "mandarin orange", "mango", "nectarine", "peach", "persimmon", "pineapple", "pomelo", "rainier cherry", "raspberry", "starfruit", "strawberry", "tangerine", "watermelon"];

cats["katsu's favorite flowers"] = ["african tulip", "azalea", "baby's breath", "bougainvillea", "carnation", "cherry blossom", "chrysanthemum", "forget-me-not", "hibiscus", "hydrangea", "jacaranda", "lily", "lotus", "lupine", "magnolia", "marigold", "morning glory", "orchid", "pansy", "peony", "poppy", "sunflower", "tulip", "water lily", "yellow trumpet"];

cats["pikmin treasures"] = ["anxious sprout", "chance totem", "citrus lump", "dimension converter", "dream architect", "drought ender", "fish-bed snack", "five-man napsack", "glinty circular disc", "jiggle-jiggle", "joy recepticle", "king of bugs", "lesser mock bottom", "memory fragment", "mystery squish fish", "portable sunset", "refreshing goo", "science project", "seed of greed", "sphere of beginnings", "sphere of fuzzy feelings", "spouse alert", "taste sensation", "thirst activator", "wiggle noggin"];

cats["piklopedia creatures"] = ["armored cannon beetle", "baldy long legs", "bulbmin", "burrowing snagret", "doodlebug", "fiery bulblax", "honeywisp", "joustmite", "lesser spotted jellyfloat", "mammoth snootwhacker", "mamuta", "man-at-legs", "puffstool", "puffy blowhog", "shearwig", "skeeterskate", "skitter leaf", "sunsquish", "swooping snitchbug", "toady bloyster", "venom dweevil", "water dumple", "waterwraith", "whiptongue bulborb", "yellow wollyhop"];

cats["anime movies & series katsu has seen"] = ["5 centimeters per second", "a silent voice", "a whisker away", "akira", "anohana: the the flower we saw that day", "beastars", "bocchi the rock", "cosmic princess kaguya", "miss kobayashi's dragon maid", "flavors of youth", "fullmetal alchemist: brotherhood", "i want to eat your pancreas", "k-on!", "little witch academia", "look back", "nausicaä of the valley of the wind", "neon genesis evangelion", "nichijou", "paprika", "perfect blue", "puella magi madoka magica", "the girl who leapt through time", "weathering with you", "wolf children", "your lie in april"];

cats["katsu's plushies"] = ["austin the whale shark", "banana the crab", "bee", "blooper", "blue axolotl", "boba the spheal", "borgy", "chef the octopus", "cutter kirby", "dream course kirby", "flybon", "friend heart kirby", "hammer kirby", "luigi the yoshi", "nemo's eg", "polite kirby", "sleepy kirby", "snomnom", "spheal the boba", "supe the frog", "tokyo station pikachu", "waddle dee", "waddle doo", "warpstar kirby", "yoshi the luigi"];

cats["streamed games"] = ["a short hike", "celeste", "dadish 2", "earthbound", "kirby 64: the crystal shards", "kirby air ride", "kirby and the forgotten land", "kirby mass attack", "kirby: squeak squad", "kirby's return to dream land deluxe", "luigi's mansion", "new pokemon snap", "paper mario", "part time ufo", "pikmin 4", "pokemon mystery dungeon: blue rescue team", "pokemon ultra sun", "super mario rpg", "super mario sunshine", "the legend of zelda: majora's mask", "the legend of zelda: ocarina of time", "the legend of zelda: skyward sword", "the legend of zelda: twilight princess", "wii sports resort", "yoshi's island"];

cats["cat subreddits"] = ["activationsound", "airplaneears", "attackeyes", "blep", "bottlebrush", "bubblegumnose", "cromch", "curledfeetsies", "danglers", "ekekek", "facehugs", "gingermafia", "greebles", "jellybeantoes", "missingorspareparts", "murdermittens", "oneorangebraincell", "scrunklynoses", "sootsprites", "spreadytoes", "teefies", "toebeans", "toefeathers", "touchthafishy", "whiskerfireworks"];

cats["weather app information"] = [""feels like" temperature", "10-day forecast", "air pressure", "air quality index", "chance of precipitation", "dew point", "first light", "hourly forecast", "humidity", "last light", "moon distance", "moon illumination percent", "moon phase", "moonrise time", "moonset time", "next full moon", "precipitation totals", "sunrise time", "sunset time", "temperature", "total daylight time", "uv index", "visibility", "wind direction", "wind speed"];

cats["atmospheric optical phenomena"] = ["airglow", "alexander's bow", "alpenglow", "anticrepuscular rays", "aurora", "belt of venus", "blue jet", "circumhorizontal arc", "cloud iridescence", "crepuscular rays", "earth's shadow", "glories", "green flash", "ice blink", "light pillar", "lightning", "mirages", "moon dog", "moonbow", "polar stratospheric cloud", "rainbow", "red sprite", "steve", "sun dog", "tangent arc"];

cats["english phonemes via international phonetic alphabet"] = ["b", "d", "dʒ", "f", "j", "m", "n", "p", "s", "t", "tʃ", "v", "w", "æ", "ð", "ŋ", "ɒ", "ə", "ɛ", "ɪ", "ʃ", "ʊ", "ʌ", "ʒ", "θ"];

cats["warrior cats characters"] = ["bluestar", "brambleclaw", "brightheart", "cinderheart", "cinderpelt", "crookedstar", "feathertail", "firestar", "frostfur", "graystripe", "hawkfrost", "hollyleaf", "ivypool", "jayfeather", "leafpool", "leopardstar", "ravenpaw", "silverstream", "spottedleaf", "squirrelflight", "stormfur", "swiftpaw", "tawnypelt", "tigerstar", "whitestorm"];

cats["US national parks"] = ["acadia", "arches", "badlands", "bryce canyon", "canyonlands", "capitol reef", "channel islands", "crater lake", "death valley", "denali", "everglades", "glacier", "grand canyon", "grand teton", "great sand dunes", "haleakalā", "joshua tree", "mount rainier", "north cascades", "olympic", "seqouia", "white sands", "yellowstone", "yosemite", "zion"];

cats["pokemon moves"] = ["aqua jet", "aura sphere", "aurora beam", "belly drum", "brave bird", "charge beam", "confusion", "dazzling gleam", "false swipe", "guillotine", "heart stamp", "helping hand", "leaf blade", "lick", "lovely kiss", "mega drain", "mirror shot", "muddy water", "nuzzle", "perish song", "powder snow", "scary face", "synthesis", "wake-up slap", "x-scissor"];

cats["kirby bosses"] = ["0²", "clawroline", "computer virus", "dark nebula", "daroach", "dyna blade", "fatty whale", "forgo dedede", "galacta knight", "galactic nova nucleus", "heavy lobster", "king dedede", "kracko", "magolor", "marx", "meta knight", "mr. dooter", "mr. shine & mr. bright", "nightmare", "paint roller", "sillydillo", "void termina", "wham bam rock", "whispy woods", "yin-yarn"];

cats["oz-isms"] = ["braverism", "clandestinedly", "confusifying", "congratulotions", "decipherate", "definish", "degreenify", "demanderating", "devastrated", "discoverate", "disgusticified", "disrespectation", "disturberance", "encouragerize", "festivating", "gratitution", "hideoteous", "horrendible", "manifestorium", "moodified", "outuendo", "rejoicify", "scandalacious", "swankified", "thrillifying"];

cats["bugs from animal crossing: new horizons"] = ["ant", "atlas moth", "blue weevil beetle", "brown cicada", "diving beetle", "dung beetle", "firefly", "flea", "hermit crab", "jewel beetle", "ladybug", "long locust", "miyama stag", "mosquito", "orchid mantis", "peacock butterfly", "queen alexandra's birdwing", "rainbow stag", "red dragonfly", "snail", "tarantula", "walking leaf", "walking stick", "wasp", "yellow butterfly"];

cats["colors in taylor swift lyrics"] = ["amber", "aquamarine", "black", "blue", "brown", "burgundy", "crimson", "gold", "gray", "green", "indigo", "key lime green", "lavender", "lilac", "mahogany", "maroon", "pale blue", "pink", "purple", "rose gold", "scarlet", "silver", "teal", "violet", "white"];
